apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticketing-dev-373117/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: ticketing-dev-373117
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
